### ISSUE TITLE
点赞数多的时候报错了，浏览器崩溃

### ISSUE THREAD

**Issue by Canyonsfr** [AlexZhangji/Twitter-Insight-LLM#1]
2024-03-08 10:42:16,951 - __main__ - INFO - Tweet: <selenium.webdriver.remote.webelement.WebElement (session="6d68c615a31a66014517db5a18a144ed", element="f.4558563DBA9B5CDD7FCE8259F38DCFD1.d.A0B7EFFDA9F1D15135C1B32CAF8A42EB.e.12597")>
Traceback (most recent call last):
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "E:\Twitter-Insight-LLM-main\twitter_data_ingestion.py", line 152, in _process_tweet
    author_name, author_handle = self._extract_author_details(tweet)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Twitter-Insight-LLM-main\twitter_data_ingestion.py", line 240, in _extract_author_details
    author_details = self._get_element_text(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Twitter-Insight-LLM-main\twitter_data_ingestion.py", line 196, in _get_element_text
    return parent.find_element(By.XPATH, selector).text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 417, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=122.0.6261.112); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF656AFAD32+56930]
	(No symbol) [0x00007FF656A6F632]
	(No symbol) [0x00007FF6569242E5]
	(No symbol) [0x00007FF656929261]
	(No symbol) [0x00007FF65692B6EB]
	(No symbol) [0x00007FF65692B7B0]
	(No symbol) [0x00007FF65696955C]
	(No symbol) [0x00007FF656969A2C]
	(No symbol) [0x00007FF65695F13C]
	(No symbol) [0x00007FF65698BCDF]
	(No symbol) [0x00007FF65695F09A]
	(No symbol) [0x00007FF65698BEB0]
	(No symbol) [0x00007FF6569A81E2]
	(No symbol) [0x00007FF65698BA43]
	(No symbol) [0x00007FF65695D438]
	(No symbol) [0x00007FF65695E4D1]
	GetHandleVerifier [0x00007FF656E76ABD+3709933]
	GetHandleVerifier [0x00007FF656ECFFFD+4075821]
	GetHandleVerifier [0x00007FF656EC818F+4043455]
	GetHandleVerifier [0x00007FF656B99766+706710]
	(No symbol) [0x00007FF656A7B90F]
	(No symbol) [0x00007FF656A76AF4]
	(No symbol) [0x00007FF656A76C4C]
	(No symbol) [0x00007FF656A66904]
	BaseThreadInitThunk [0x00007FF8AB1B7344+20]
	RtlUserThreadStart [0x00007FF8ABE026B1+33]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Twitter-Insight-LLM-main\twitter_data_ingestion.py", line 311, in <module>
    scraper.fetch_tweets(
  File "E:\Twitter-Insight-LLM-main\twitter_data_ingestion.py", line 55, in fetch_tweets
    row = self._process_tweet(tweet)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc\PycharmProjects\pythonProject\.venv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x173c9675e80 state=finished raised StaleElementReferenceException>]

**Comment by xigaohu** [comment]
在 options.headless = headless 的下面添加一句 `options.add_argument('--no-sandbox')` 试一试
